import combo from './combo(2).jpg'
import combo from './combo(3).jpg'
import combo from './combo(4).jpg'
import combo from './combo(5).jpg'
import combo from './combo.jpg'
import couple from './couple-cups.jpg'
import couple from './couple-cups(2).jpg'
import couple from './couple-cups(3).jpg'
import couple from './couple-cups(4).jpg'
import ctshirts from './couple-tshirts.jpg'
import ctshirts from './couple-tshirts(2).jpg'
import ctshirts from './couple-tshirts(3).jpg'
import ctshirts from './couple-tshirts(4).jpg'
import hbags from './hand-bags.jpg'
import hbags from './hand-bags(2).jpg'
import hbags from './hand-bags(3).jpg'
import hbags from './hand-bags(4).jpg'
import sbags from './school-bags.jpg'
import sbags from './school-bags.jpg'
import kchain from './key-chain.jpg'
import kchain from './key-chain(2).jpg'
import kchain from './key-chain(3).jpg'
import kchain from './key-chain(4).jpg'
import kjersy from './kids-jersy.jpg'
import kjersy from './kids-jersy(2).jpg'
import kjersy from './kids-jersy(3).jpg'
import kjersy from './kids-jersy(4).jpg'
import ktshirts from './kids-tshirts.jpg'
import ktshirts from './kids-tshirts(2).jpg'
import ktshirts from './kids-tshirts(3).jpg'
import mug from './mugs.jpg'
import mug from './mugs(2).jpg'
import pillow from './pillow.jpg'
import pillow from './pillow(2).jpg'
import pillow from './pillow(3).jpg'
import pillow from './pillow(4).jpg'
import pillow from './pillow(5).jpg'
import logo from './logo.jpg'





